# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JTCalendarProgrammatic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JTCalendarProgrammatic
pod 'JTAppleCalendar', '~> 7.0.4'
  target 'JTCalendarProgrammaticTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JTCalendarProgrammaticUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
