# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Gifty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'JTAppleCalendar', '~> 7.1'
pod 'RKPieChart', '~> 0.0'
pod 'Google-Mobile-Ads-SDK'

  # Pods for Gifty

  target 'GiftyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GiftyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
